GET http://localhost:3000/pets

###

GET http://localhost:3000/pets/3

###

POST http://localhost:3000/pets
content-type: application/json

{
  "id": 5,
  "name": "Princess",
  "age": 2,
  "breed": "Golden Retriever",
  "color": "Brown",
  "gender": "Female"
}

###

PUT http://localhost:3000/pets/3
content-type: application/json

{
  "id": 3,
  "name": "Princess",
  "age": 3,
  "breed": "Golden Retriever",
  "color": "Golden",
  "gender": "Female"
}

### 

DELETE http://localhost:3000/pets/3

###

POST http://localhost:3000/users
content-type: application/json

{
  "email": "john@inter.net",
  "password": "123456",
  "name": "John Doe"
}

###

GET http://localhost:3000/users/9

###

PATCH http://localhost:3000/users/9
content-type: application/json

{
  "email": "john@inter.net",
  "password": "Mudar@123",
  "name": "John Doe"
}


###

DELETE http://localhost:3000/users/9