GET http://localhost:3000/pets

###

GET http://localhost:3000/pets/1

###

POST http://localhost:3000/pets
content-type: application/json

{
  "id": 3,
  "name": "Princess",
  "age": 2,
  "breed": "Golden Retriever",
  "color": "Brown",
  "gender": "Female"
}

###

PUT http://localhost:3000/pets/1
content-type: application/json

{
  "id": 1,
  "name": "Princess",
  "age": 2,
  "breed": "Golden Retriever",
  "color": "Brown",
  "gender": "Female"
}

### 

DELETE http://localhost:3000/pets/1