# @name createUser
POST http://localhost:3000/users
content-type: application/json

{
  "email": "john@inter.net",
  "password": "123456",
  "name": "John Doe"
}

###

# @name login
POST http://localhost:3000/token
content-type: application/json

{
  "email": "john@inter.net",
  "password": "123456"
}

### 

@userId = {{createUser.response.body.id}}
@authToken = {{login.response.body.token}}

###

### USERS

GET http://localhost:3000/users/{{userId}}
authorization: Bearer {{authToken}}

###

PATCH http://localhost:3000/users/{{userId}}
authorization: Bearer {{authToken}}
content-type: application/json

{
  "email": "john@inter.net",
  "password": "Mudar@123",
  "name": "John Doe"
}

###

DELETE http://localhost:3000/users/{{userId}}
authorization: Bearer {{authToken}}

###

### PETS

GET http://localhost:3000/pets
authorization: Bearer {{authToken}}

###

# @name createPet
POST http://localhost:3000/pets
authorization: Bearer {{authToken}}
content-type: application/json

{
  "id": 5,
  "name": "Princess",
  "age": 2,
  "breed": "Golden Retriever",
  "color": "Brown",
  "gender": "Female"
}

###

@petId = {{createPet.response.body.id}}

###

GET http://localhost:3000/pets/{{petId}}
authorization: Bearer {{authToken}}

###

PUT http://localhost:3000/pets/{{petId}}
authorization: Bearer {{authToken}}
content-type: application/json

{
  "id": 3,
  "name": "Princess",
  "age": 3,
  "breed": "Golden Retriever",
  "color": "Golden",
  "gender": "Female"
}

### 

DELETE http://localhost:3000/pets/{{petId}}
authorization: Bearer {{authToken}}

###