services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=Pets
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080